extends RefCounted
class_name ThemePalette
## 清新高级风主题色（计划书定稿），供 StyleBoxFlat / 字体色

const PALETTES := {
	"forest": {
		"bg_top": Color("#f5f8f6"),
		"bg_bottom": Color("#e9f0ec"),
		"card": Color("#ffffff"),
		"card_border": Color("#e0e8e3"),
		"shadow": Color(20 / 255.0, 35 / 255.0, 26 / 255.0, 0.10),
		"panel": Color("#f3f7f5"),
		"panel_border": Color("#d0ddd6"),
		"panel_hover": Color("#e8f0eb"),
		"panel_pressed": Color("#dfeae3"),
		"primary": Color("#16221c"),
		"muted": Color("#5e6d66"),
		"accent": Color("#2f6f5c"),
		"accent_hover": Color("#285e4e"),
		"accent_pressed": Color("#214c40"),
		"on_accent": Color("#ffffff"),
		"grid_line": Color("#bccdc2"),
		"cell": Color("#ffffff"),
		"cell_alt": Color("#f4f8f6"),
		"fixed": Color("#dfede5"),
		"key_border": Color("#9a7a1e"),
		"error": Color("#b3261e"),
	},
	"ocean": {
		"bg_top": Color("#f3f8fc"),
		"bg_bottom": Color("#e6f0f8"),
		"card": Color("#ffffff"),
		"card_border": Color("#dde8f2"),
		"shadow": Color(15 / 255.0, 36 / 255.0, 48 / 255.0, 0.10),
		"panel": Color("#f0f6fb"),
		"panel_border": Color("#c8daea"),
		"panel_hover": Color("#e4eef7"),
		"panel_pressed": Color("#d9e6f2"),
		"primary": Color("#142a3d"),
		"muted": Color("#5a6b7a"),
		"accent": Color("#1e6faf"),
		"accent_hover": Color("#195f96"),
		"accent_pressed": Color("#144f7d"),
		"on_accent": Color("#ffffff"),
		"grid_line": Color("#aec4d6"),
		"cell": Color("#ffffff"),
		"cell_alt": Color("#f2f7fb"),
		"fixed": Color("#ddeaf5"),
		"key_border": Color("#9a7a1e"),
		"error": Color("#b3261e"),
	},
	"dawn": {
		"bg_top": Color("#fcf9f6"),
		"bg_bottom": Color("#f5ede6"),
		"card": Color("#ffffff"),
		"card_border": Color("#e8dfdb"),
		"shadow": Color(42 / 255.0, 24 / 255.0, 16 / 255.0, 0.08),
		"panel": Color("#faf6f2"),
		"panel_border": Color("#ddd3c8"),
		"panel_hover": Color("#f2ebe4"),
		"panel_pressed": Color("#eae3db"),
		"primary": Color("#2a2218"),
		"muted": Color("#6f6359"),
		"accent": Color("#c15c3a"),
		"accent_hover": Color("#a84e32"),
		"accent_pressed": Color("#8f422a"),
		"on_accent": Color("#fffdfc"),
		"grid_line": Color("#d4c4b8"),
		"cell": Color("#ffffff"),
		"cell_alt": Color("#faf6f2"),
		"fixed": Color("#f0e4da"),
		"key_border": Color("#8a6a18"),
		"error": Color("#b3261e"),
	},
	"dusk": {
		"bg_top": Color("#f7f5fa"),
		"bg_bottom": Color("#edeaf4"),
		"card": Color("#ffffff"),
		"card_border": Color("#e2ddeb"),
		"shadow": Color(26 / 255.0, 16 / 255.0, 40 / 255.0, 0.10),
		"panel": Color("#f4f2f8"),
		"panel_border": Color("#d0c8de"),
		"panel_hover": Color("#eae6f2"),
		"panel_pressed": Color("#e0dbec"),
		"primary": Color("#221e2e"),
		"muted": Color("#656072"),
		"accent": Color("#5c4d96"),
		"accent_hover": Color("#4e4280"),
		"accent_pressed": Color("#40376a"),
		"on_accent": Color("#ffffff"),
		"grid_line": Color("#c4bad4"),
		"cell": Color("#ffffff"),
		"cell_alt": Color("#f6f4fa"),
		"fixed": Color("#e8e2f2"),
		"key_border": Color("#806611"),
		"error": Color("#b3261e"),
	},
}


static func get_palette(theme_id: String) -> Dictionary:
	if PALETTES.has(theme_id):
		return PALETTES[theme_id]
	return PALETTES["forest"]
