extends RefCounted
class_name ThemePalette
## 清新高级风主题色；含主界面专用 menu_* 键

const PALETTES := {
	"forest": {
		"bg_top": Color("#f5f8f6"),
		"bg_bottom": Color("#e9f0ec"),
		"card": Color("#ffffff"),
		"card_border": Color("#e0e8e3"),
		"shadow": Color(20 / 255.0, 35 / 255.0, 26 / 255.0, 0.10),
		"panel": Color("#f3f7f5"),
		"panel_border": Color("#d0ddd6"),
		"panel_hover": Color("#e8f0eb"),
		"panel_pressed": Color("#dfeae3"),
		"primary": Color("#16221c"),
		"muted": Color("#5e6d66"),
		"accent": Color("#2f6f5c"),
		"accent_hover": Color("#285e4e"),
		"accent_pressed": Color("#214c40"),
		"on_accent": Color("#ffffff"),
		"grid_line": Color("#bccdc2"),
		"cell": Color("#ffffff"),
		"cell_alt": Color("#f4f8f6"),
		"fixed": Color("#dfede5"),
		"key_border": Color("#9a7a1e"),
		"error": Color("#b3261e"),
		"menu_title": Color("#0a2218"),
		"menu_subtitle": Color("#5f756c"),
		"menu_row_label": Color("#2a6b52"),
		"menu_option_fg": Color("#143127"),
		"menu_panel": Color("#f5faf7"),
		"menu_panel_border": Color("#b8d5c8"),
		"menu_panel_hover": Color("#eaf5ef"),
		"menu_panel_pressed": Color("#dfeee6"),
		"menu_play_bg": Color("#ffffff"),
		"menu_play_bg_hover": Color("#ecf6f1"),
		"menu_play_bg_pressed": Color("#ddeee4"),
		"menu_play_text": Color("#2f6f5c"),
	},
	"ocean": {
		"bg_top": Color("#f3f8fc"),
		"bg_bottom": Color("#e6f0f8"),
		"card": Color("#ffffff"),
		"card_border": Color("#dde8f2"),
		"shadow": Color(15 / 255.0, 36 / 255.0, 48 / 255.0, 0.10),
		"panel": Color("#f0f6fb"),
		"panel_border": Color("#c8daea"),
		"panel_hover": Color("#e4eef7"),
		"panel_pressed": Color("#d9e6f2"),
		"primary": Color("#142a3d"),
		"muted": Color("#5a6b7a"),
		"accent": Color("#1e6faf"),
		"accent_hover": Color("#195f96"),
		"accent_pressed": Color("#144f7d"),
		"on_accent": Color("#ffffff"),
		"grid_line": Color("#aec4d6"),
		"cell": Color("#ffffff"),
		"cell_alt": Color("#f2f7fb"),
		"fixed": Color("#ddeaf5"),
		"key_border": Color("#9a7a1e"),
		"error": Color("#b3261e"),
		"menu_title": Color("#0a2540"),
		"menu_subtitle": Color("#5f6f82"),
		"menu_row_label": Color("#1c6ca8"),
		"menu_option_fg": Color("#0f2f45"),
		"menu_panel": Color("#f3f9fd"),
		"menu_panel_border": Color("#b0cce4"),
		"menu_panel_hover": Color("#e6f2fb"),
		"menu_panel_pressed": Color("#d9eaf8"),
		"menu_play_bg": Color("#ffffff"),
		"menu_play_bg_hover": Color("#ecf4fc"),
		"menu_play_bg_pressed": Color("#dde8f6"),
		"menu_play_text": Color("#1e6faf"),
	},
	"dawn": {
		"bg_top": Color("#fcf9f6"),
		"bg_bottom": Color("#f5ede6"),
		"card": Color("#ffffff"),
		"card_border": Color("#e8dfdb"),
		"shadow": Color(42 / 255.0, 24 / 255.0, 16 / 255.0, 0.08),
		"panel": Color("#faf6f2"),
		"panel_border": Color("#ddd3c8"),
		"panel_hover": Color("#f2ebe4"),
		"panel_pressed": Color("#eae3db"),
		"primary": Color("#2a2218"),
		"muted": Color("#6f6359"),
		"accent": Color("#c15c3a"),
		"accent_hover": Color("#a84e32"),
		"accent_pressed": Color("#8f422a"),
		"on_accent": Color("#fffdfc"),
		"grid_line": Color("#d4c4b8"),
		"cell": Color("#ffffff"),
		"cell_alt": Color("#faf6f2"),
		"fixed": Color("#f0e4da"),
		"key_border": Color("#8a6a18"),
		"error": Color("#b3261e"),
		"menu_title": Color("#3d2316"),
		"menu_subtitle": Color("#7d6e62"),
		"menu_row_label": Color("#a8482c"),
		"menu_option_fg": Color("#3a261c"),
		"menu_panel": Color("#fcf8f4"),
		"menu_panel_border": Color("#e5d5c8"),
		"menu_panel_hover": Color("#f5ebe3"),
		"menu_panel_pressed": Color("#ece2d9"),
		"menu_play_bg": Color("#ffffff"),
		"menu_play_bg_hover": Color("#fdf5f0"),
		"menu_play_bg_pressed": Color("#f5e8df"),
		"menu_play_text": Color("#b84528"),
	},
	"dusk": {
		"bg_top": Color("#f7f5fa"),
		"bg_bottom": Color("#edeaf4"),
		"card": Color("#ffffff"),
		"card_border": Color("#e2ddeb"),
		"shadow": Color(26 / 255.0, 16 / 255.0, 40 / 255.0, 0.10),
		"panel": Color("#f4f2f8"),
		"panel_border": Color("#d0c8de"),
		"panel_hover": Color("#eae6f2"),
		"panel_pressed": Color("#e0dbec"),
		"primary": Color("#221e2e"),
		"muted": Color("#656072"),
		"accent": Color("#5c4d96"),
		"accent_hover": Color("#4e4280"),
		"accent_pressed": Color("#40376a"),
		"on_accent": Color("#ffffff"),
		"grid_line": Color("#c4bad4"),
		"cell": Color("#ffffff"),
		"cell_alt": Color("#f6f4fa"),
		"fixed": Color("#e8e2f2"),
		"key_border": Color("#806611"),
		"error": Color("#b3261e"),
		"menu_title": Color("#1a1526"),
		"menu_subtitle": Color("#6d6679"),
		"menu_row_label": Color("#4d4190"),
		"menu_option_fg": Color("#2a2238"),
		"menu_panel": Color("#f7f5fb"),
		"menu_panel_border": Color("#cbc0dc"),
		"menu_panel_hover": Color("#edeaf6"),
		"menu_panel_pressed": Color("#e3dfef"),
		"menu_play_bg": Color("#ffffff"),
		"menu_play_bg_hover": Color("#f2eff9"),
		"menu_play_bg_pressed": Color("#e8e3f4"),
		"menu_play_text": Color("#5c4d96"),
	},
}


static func get_palette(theme_id: String) -> Dictionary:
	if PALETTES.has(theme_id):
		return PALETTES[theme_id]
	return PALETTES["forest"]
